<a href="https://colab.research.google.com/github/mvharsh/Mathematical-Computing/blob/main/Transportation_Problem.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **FIND OPTIMUM SOLUTION FOR BALANCED AND UNBALANCED TRANSPORTATION PROBLEMS**


**AIM:**

To solve balanced and unbalanced transportation problems by finding initial feasible solutions using the Northwest Corner and Least Cost methods.


**ALGORITHM:**

1.	**Input:** Get cost matrix, supply, and demand.
2.	**Balance:** Check and balance the problem by adding dummy rows/columns if needed.
3.	**Northwest Corner:** Allocate maximum possible units starting from the top-left cell until supply/demand is met.
4.	**Least Cost:** Allocate maximum possible units to the cell with the minimum cost until supply/demand is met, excluding assigned rows/columns.
5.	**Output:** Display allocation matrices and total costs for both methods.


In [ ]:
import numpy as np

def check_balanced(supply, demand):
    """Check if the transportation problem is balanced"""
    return sum(supply) == sum(demand)

def balance_problem(cost_matrix, supply, demand):
    """Balance the transportation problem by adding dummy row/column"""
    supply = supply.copy()
    demand = demand.copy()
    cost = cost_matrix.copy()

    if sum(supply) > sum(demand):
        diff = sum(supply) - sum(demand)
        cost = np.column_stack((cost, np.zeros(len(supply))))
        demand = np.append(demand, diff)
    elif sum(supply) < sum(demand):
        diff = sum(demand) - sum(supply)
        cost = np.vstack((cost, np.zeros(len(demand))))
        supply = np.append(supply, diff)

    return cost, supply, demand

def northwest_corner(supply, demand):
    """Northwest Corner Rule Method"""
    supply = supply.copy()
    demand = demand.copy()
    m, n = len(supply), len(demand)
    allocation = np.zeros((m, n))

    i, j = 0, 0
    while i < m and j < n:
        quantity = min(supply[i], demand[j])
        allocation[i, j] = quantity
        supply[i] -= quantity
        demand[j] -= quantity

        if supply[i] == 0:
            i += 1
        if demand[j] == 0:
            j += 1

    return allocation

def least_cost(cost_matrix, supply, demand):
    """Least Cost Entry Method"""
    supply = supply.copy()
    demand = demand.copy()
    cost = cost_matrix.copy()
    m, n = cost.shape
    allocation = np.zeros((m, n))

    while True:
        if np.all(supply == 0) and np.all(demand == 0):
            break

        valid_cells = np.where((cost < float('inf')) & (cost >= 0))
        if len(valid_cells[0]) == 0:
            break

        min_cost_idx = np.argmin(cost[valid_cells])
        i, j = valid_cells[0][min_cost_idx], valid_cells[1][min_cost_idx]

        quantity = min(supply[i], demand[j])
        allocation[i, j] = quantity
        supply[i] -= quantity
        demand[j] -= quantity

        if supply[i] == 0:
            cost[i, :] = float('inf')
        if demand[j] == 0:
            cost[:, j] = float('inf')

    return allocation

def main():
    print("\nTransportation Problem Solver")

    m = int(input("Enter number of sources: "))
    n = int(input("Enter number of destinations: "))

    print("\nEnter cost matrix:")
    cost_matrix = np.zeros((m, n))
    for i in range(m):
        row = input(f"Enter costs for source {i+1} (space-separated): ").split()
        cost_matrix[i] = [float(x) for x in row]

    print("\nEnter supply values:")
    supply = np.array([float(input(f"Supply for source {i+1}: ")) for i in range(m)])

    print("\nEnter demand values:")
    demand = np.array([float(input(f"Demand for destination {i+1}: ")) for i in range(n)])

    is_balanced = check_balanced(supply, demand)
    print(f"\nProblem is {'balanced' if is_balanced else 'unbalanced'}")

    if not is_balanced:
        cost_matrix, supply, demand = balance_problem(cost_matrix, supply, demand)
        print("Problem has been balanced")

    nw_allocation = northwest_corner(supply, demand)
    nw_cost = np.sum(nw_allocation * cost_matrix)

    print("\nNorthwest Corner Rule Method Solution:")
    print(nw_allocation)
    print(f"Total Cost: {nw_cost}")

    lc_allocation = least_cost(cost_matrix, supply, demand)
    lc_cost = np.sum(lc_allocation * cost_matrix)

    print("\nLeast Cost Entry Method Solution:")
    print(lc_allocation)
    print(f"Total Cost: {lc_cost}")

if __name__ == "__main__":
    main()



Transportation Problem Solver
Enter number of sources: 4
Enter number of destinations: 5

Enter cost matrix:
Enter costs for source 1 (space-separated): 5 1 8 7 5
Enter costs for source 2 (space-separated): 3 9 6 7 8
Enter costs for source 3 (space-separated): 4 2 7 6 5
Enter costs for source 4 (space-separated): 7 11 10 4 9

Enter supply values:
Supply for source 1: 15 
Supply for source 2: 25
Supply for source 3: 42
Supply for source 4: 35

Enter demand values:
Demand for destination 1: 30
Demand for destination 2: 20
Demand for destination 3: 15
Demand for destination 4: 10
Demand for destination 5: 20

Problem is unbalanced
Problem has been balanced

Northwest Corner Rule Method Solution:
[[15.  0.  0.  0.  0.  0.]
 [15. 10.  0.  0.  0.  0.]
 [ 0. 10. 15. 10.  7.  0.]
 [ 0.  0.  0.  0. 13. 22.]]
Total Cost: 547.0

Least Cost Entry Method Solution:
[[ 0.  0.  0.  0.  0. 15.]
 [18.  0.  0.  0.  0.  7.]
 [12. 20.  0.  0. 10.  0.]
 [ 0.  0. 15. 10. 10.  0.]]
Total Cost: 472.0
